import { type NextPage } from "next";
import Head from "next/head";
// import Link from "next/link";
// import { api } from "../utils/api";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="to-primary-accent flex min-h-screen flex-col bg-gradient-to-b from-primary pt-28">
        <div className="container">
          <div className="flex flex-col items-center justify-center gap-4">
            <h1 className="text-6xl font-bold text-white">New items</h1>
            <p className="text-center text-2xl text-white"></p>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
